# Generated by Django 2.1.5 on 2020-01-20 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200120_0524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='sirname',
        ),
    ]
