# Generated by Django 2.1.5 on 2020-01-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
