# Generated by Django 2.1.5 on 2020-01-24 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_plan_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='city_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.City'),
        ),
    ]
