# Generated by Django 2.1.5 on 2020-01-21 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='moving_method',
            new_name='first_place',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='third_place',
        ),
    ]
