# Generated by Django 2.1.5 on 2020-01-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200122_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='name',
            new_name='user',
        ),
    ]
